version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 498982086513.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t sar-api .
      - docker tag sar-api:latest 498982086513.dkr.ecr.us-east-2.amazonaws.com/sar-api:latest
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push 498982086513.dkr.ecr.us-east-2.amazonaws.com/sar-api:latest
